In [9]:
import os
import tensorflow as tf
from tensorflow_transform.tf_metadata import dataset_metadata, metadata_io,dataset_schema 
from tensorflow_transform.beam.tft_beam_io import transform_fn_io
tf.enable_eager_execution()

In [10]:
def transform_metadata(folder="gs://relation_extraction/beam/"):
    """Read the transform metadata"""
    transformed_metadata = metadata_io.read_metadata(
    os.path.join(
        folder, transform_fn_io.TRANSFORMED_METADATA_DIR
            )
        )
    transformed_feature_spec = transformed_metadata.schema.as_feature_spec()
    return transformed_feature_spec
schema = transform_metadata()

AbortedError: All 10 retry attempts failed. The last failure: Unavailable: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Couldn't resolve host 'www.googleapis.com'
	 when reading metadata of gs://relation_extraction/beam/transformed_metadata/v1-json/schema.json

In [ ]:
raw_dataset = tf.data.TFRecordDataset(r'gs://relation_extraction/beam/Test/TEST-00001-of-00002')

def _parse_image_function(example_proto):
  # Parse the input tf.Example proto using the dictionary above.
  return tf.parse_single_example(example_proto, schema)

parsed_image_dataset = raw_dataset.map(_parse_image_function).batch(10)
parsed_image_dataset

In [ ]:
for id,image_features in enumerate(parsed_image_dataset):
    image_raw = image_features.keys()

In [ ]:
def padd(input_tensor=None,tensor_length=None):
    """Functon to padd the inputs with"""
    paddings = tf.constant([[0, 0,], [0,tensor_length]])
    input_tensor = tf.pad(input_tensor,paddings,"CONSTANT")
    output_tensor = tf.slice(input_tensor,[0,0],[tf.shape(input_tensor)[0],tensor_length])
    return output_tensor

In [ ]:
image_features["word_representation"]

In [ ]:
tf.shape(sentence)

In [7]:
sentence = tf.sparse.to_dense(image_features["word_representation"],default_value=0)
paddings = tf.constant([[0, 0,], [0,50]])
input_tensor = tf.pad(sentence,paddings,"CONSTANT")
input_tensor

Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.


<tf.Tensor: id=248, shape=(7, 143), dtype=int64, numpy=
array([[  35,   57,  433, ...,    0,    0,    0],
       [  90,   18,    1, ...,    0,    0,    0],
       [   0,    0,    2, ...,    0,    0,    0],
       ...,
       [  40,    1,  871, ...,    0,    0,    0],
       [   1, 2150,   33, ...,    0,    0,    0],
       [ 908,    3,   36, ...,    0,    0,    0]])>

In [13]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
paddings = tf.constant([[0, 0,], [0, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
out = tf.pad(t, paddings, "CONSTANT")
out

<tf.Tensor: id=261, shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 3, 0, 0],
       [4, 5, 6, 0, 0]], dtype=int32)>

In [28]:
output_tensor = tf.slice(out,[0,0],[tf.shape(out)[0],4])
output_tensor

<tf.Tensor: id=333, shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 0],
       [4, 5, 6, 0]], dtype=int32)>

In [15]:
input_sentences = padd(sentence,50)

InvalidArgumentError: The first dimension of paddings must be the rank of inputs[2,2] [22] [Op:Pad]

In [5]:
!gsutil ls gs://relation_extraction/beam/Train/TRAIN-00000-of-00002

gs://relation_extraction/beam/Train/TRAIN-00000-of-00002


In [13]:
raw_dataset

<TFRecordDataset shapes: (), types: tf.string>